name: GoodMorning
on:
  workflow_dispatch:
    branches:
      - master
  schedule:
    # `分 时 天 月 周` 时按照标准时间 北京时间=标准时间+8 18表示北京时间早上2点
    - cron: '* * * * *'
# on:
#   push:
#     branches:
#       - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # 2. 设置pnpm包管理器
      - name: curl daliy notice
        run: |
        echo "curl daliy.carlsonsoft.cn"
        curl daliy.carlsonsoft.cn
